### PR TITLE
Fixed the import paths.

### PR DESCRIPTION
**Pull request by Skarlso**

### CODE REVIEW

**Comment by karel-3d** [comment]
Why do Skarlso/html-to-markdown plugins import arangodb-managed/html-to-markdown?

This makes no sense :D I want to use Skarlso/html-to-markdown , not arangodb-managed/html-to-markdown

**Comment by karel-3d** [comment]
should I use arangodb-managed instead?

**Comment by Skarlso** [comment]
@karel-3d Oh, I think that's a mistake on my part. I will fix that for you. :)

**Comment by Skarlso** [comment]
@karel-3d As a quick fix you can use this commit: https://github.com/Skarlso/html-to-markdown/commit/2cf06e949e49e47a905336fb83fb03fc96f71dd3

For now. I will revert both commits after that.

**Comment by Skarlso** [comment]
@karel-3d should now be fixed. Sorry for the inconvenience.

**Comment by karel-3d** [comment]
which one of the two will be maintained long term? :D

**Comment by Skarlso** [comment]
This is my own. But I'm not expecting to do too much with it to be honest. It just works right now for my oor arango's purposes. 😊

**Pull request merged**
